### ISSUE TITLE
Radiation Not Working

### ISSUE THREAD

**Issue by DinoNuggets2** [Marco15453/NukeLock#11]
**Describe the bug**
Radiation does not occur at the specific time set after the warhead detonates.

**To Reproduce**
1. Detonate the warhead
2. Wait for the radiation to begin

**Expected behavior**
Expecting radiation to occur at the designated time after the warhead detonates.

**Screenshots**

**Server logs**
https://pastebin.com/w8icdHFE

**NukeLock Version ("latest" is not a version):**
1.8.2

**Results of `show plugins` command in console:**
                           Enabled plugins: 36
                           Disabled plugins: 0
                           
                           CedMod:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm
                                - Priority: Highest
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           Spectator Shooting Range:
                                - Author: rayzer
                                - Version: 2.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: spectator_shooting_range
                                - Priority: Higher
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           CustomBreachScenarios:
                                - Author: Cegla
                                - Version: 1.0.1
                                - Required Exiled Version: 4.2.2
                                - Prefix: CustomBreachScenarios
                                - Priority: Medium
                           SummonRespawnVehicles:
                                - Author: 
                                - Version: 1.0.0.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: summon_respawn_vehicles
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           CedMod-Events:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_events
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK && Raul125
                                - Version: 3.3.0
                                - Required Exiled Version: 4.2.3
                                - Prefix: ST106
                                - Priority: Medium
                           Infiltrated:
                                - Author: Twitch.tv/Monaldcry7788#9248
                                - Version: 5.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: infiltrated
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 4.1.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           LightsRE:
                                - Author: Beryl - (Contributors: BuildBoy12)
                                - Version: 4.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: lights
                                - Priority: Medium
                           CedMod-WebAPI:
                                - Author: ced777ric#8321
                                - Version: 3.0.2
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_WAPI
                                - Priority: Medium
                           Scp035:
                                - Author: Joker119
                                - Version: 4.0.2
                                - Required Exiled Version: 4.2.0
                                - Prefix: Scp035
                                - Priority: Medium
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           BetterDrops:
                                - Author: Jesus-QC
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7
                                - Prefix: better_drops
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.8.2
                                - Required Exiled Version: 4.2.2
                                - Prefix: nuke_lock
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 2.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.2.0
                                - Required Exiled Version: 4.2.3
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           CedMod-SampleEvent:
                                - Author: ced777ric#8321
                                - Version: 0.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: cm_sampleevent
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.2.3.0
                                - Required Exiled Version: 4.2.3.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest
**Additional context**

**Comment by Marco15453** [comment]
Can you provide an Video that proofes this issue

**Comment by DinoNuggets2** [comment]
https://user-images.githubusercontent.com/91291118/151672028-236cf6ec-21d6-4d45-b3b5-be1935f7e6b7.mp4

**Comment by Marco15453** [comment]
Can you send me your config?

**Comment by DinoNuggets2** [comment]
nuke_lock:
# Should the plugin be enabled?
  is_enabled: true
  # Should the Warhead be armed at the start of the Round?
  warhead_auto_armed: true
  # Should the Warhead be locked at the start of the Round?
  warhead_cancelable: false
  # Death Message when the player gets killed by Radiation.
  radiation_death_reason: Died by Radiation
  # After which delay should radiation start when the warhead detonated. (-1 = Disabled)
  radiation_delay: 120
  # Message to be shown when the Warhead Detonated. (Empty = Disabled)
  radiation_warning_message: <color=red>Radiation leak will begin on surface in 2 minutes from the warhead</color>
  # Message to be shown when the Radiation has occured. (Empty = Disabled)
  radiation_begin_message: <color=red>Radiation leak has begun on surface zone</color>
  # The Interval that the radiation_damage will be dealth to all players after the warhead detonates.
  radiation_interval: 2
  # The Damage dealth to players after each radiation_interval
  radiation_damage: 5
  # After what time should the warhead be automaticly started and can't be stopped (-1 = Disabled)
  auto_nuke: 1800
  # After what autonuke time should a permanently broadcast be broadcasted across the map to tell the AutoNuke will be activated? %COUNTDOWN% will be replaced with the time left until autonuke will be activated
  auto_nuke_perma_broadcast_timer: 10
  auto_nuke_perma_broadcast_message: <color=red>Omega Warhead Emergency Detonation Sequence will engage in %COUNTDOWN% seconds</color>
  # How long should the Hint be displayed when a player tries to disable the Nuke while it can't be stopped? (-1 = Disabled)
  hint_time: 3
  # What hint should be displayed when a player tries to disable the nuke while it can't be stopped?
  hint_message: <color=red>The omega warhead cannot be cancelled!</color>
  # How long should a broadcast be broadcasted when the AutoNuke activates? (-1 = Disabled)
  detonation_broadcast_time: 3
  # What broadcast should be broadcasted when the AutoNuke activates?
  detonation_broadcast_message: <color=red>The Omega Warhead Detonation Sequence engaged, <b>This Warhead cannot be stopped</b></color>
  # Whether or not a broadcast will be shown to all players to tell how many seconds are remaining until the warhead explodes.
  warhead_detonation_timer: false
  # Message to be shown to tell players how many seconds are remaining until the warhead explodes. %COUNTDOWN% will be replaced with the seconds until the warhead detonates
  warhead_detonation_message: <color=red>Omega Warhead detonates in T-Minus</color> <color=orange>%COUNTDOWN% seconds</color>
  # Whether or not team respawning will be disabled when the warhead detonated.
  warhead_disables_team_respawn: true
  # What Color should the warhead have when the warhead starts. (Putting one to -1 will disable it)
  warhead_color:
    red: -1
    green: 255
    blue: 255
  # After what time should a cassie message be broadcasted? (Empty = Disabled)
  cassie_warnings:
    1500: Attention all personnel . The Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 25 Minutes
    1200: pitch_0.2 .g4 . pitch_1 . Danger . Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 20 Minutes
    900: pitch_0.2 .g4 . pitch_1 . Danger . Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 15 Minutes
    600: pitch_0.2 .g4 . pitch_1 . Danger . Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 10 minutes
    300: pitch_0.2 .g4 . pitch_1 . Danger . Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 5 Minutes . starting evacuation procedure
    60: pitch_0.2 .g4 . pitch_1 . Danger . Omega Warhead Emergency Detonation Sequence will be engaged in TMinus 1 Minute . Evacuate Now

**Comment by DinoNuggets2** [comment]
https://pastebin.com/4kBkS3SW

**Comment by DinoNuggets2** [comment]
Hi, just a quick check, do you know if this is a plugin issue or a plugin interfearing with it? I am doing a server update soon, and I can remove any plugins that might interfear.

**Comment by Marco15453** [comment]
It seems to be a plugin issue, please wait I'm still investigating it.
