### ISSUE TITLE
[BUG] Sometimes auto nuke starts when round starts

### ISSUE THREAD

**Issue by Lazyas** [Marco15453/NukeLock#13]
**Describe the bug**
When round starts auto nuke is starting almost immediately. You Can't turn off the nuke too

**To Reproduce**
1. start the round
42 See error

**Expected behavior**
AUTO NUKE starts what the owner set timer to.

**Screenshots**
i forgot to took screenshots sorry.

**Server logs**
I turned off the localadmin logs soooo yea

**NukeLock Version ("latest" is not a version):**
v.1.10.0

**Results of `show plugins` command in console:**
[2022-05-03 14:23:04.471 +00:00] Total number of plugins: 24
                                 Enabled plugins: 23
                                 Disabled plugins: 1
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 5.2.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 MapEditorReborn:
                                        - Author: Michal78900 (original idea by Killers0992)
                                        - Version: 2.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: map_editor_reborn
                                        - Priority: Medium
                                 ScpSwap:
                                        - Author: Build
                                        - Version: 1.1.2
                                        - Required Exiled Version: 5.1.3
                                        - Prefix: ScpSwap
                                        - Priority: Medium
                                 InfiniteRadio:
                                        - Author: Build
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: infinite_radio
                                        - Priority: Medium
                                 CuffedTK:
                                        - Author: Marco15453
                                        - Version: 1.11.0
                                        - Required Exiled Version: 5.1.3
                                        - Prefix: CTK
                                        - Priority: Medium
                                 WhoAreMyTeammates:
                                        - Author: XoMiya-WPC & TheUltiOne
                                        - Version: 4.0.3
                                        - Required Exiled Version: 4.2.3
                                        - Prefix: WhoAreMyTeammates
                                        - Priority: Medium
                                 KillLogs:
                                        - Author: 0b10000
                                        - Version: 3.0.1
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: KillLogs
                                        - Priority: Medium
                                 WaitAndChillReborn:
                                        - Author: Michal78900
                                        - Version: 5.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: wait_and_chill_reborn
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Galaxy119
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 SpectatorList:
                                        - Author: TTypiarz
                                        - Version: 1.1.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: SpectatorList
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 5.2.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Author: Exiled Team
                                        - Version: 5.0.5.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 5.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Disabled
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 MvpUtility:
                                        - Author: Undid-Iridium
                                        - Version: 1.0.7
                                        - Required Exiled Version: 5.1.3
                                        - Prefix: mvp_utility
                                        - Priority: Medium
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 3.1.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Medium
                                 NukeLock:
                                        - Author: Marco15453
                                        - Version: 1.10.0
                                        - Required Exiled Version: 5.1.3
                                        - Prefix: nuke_lock
                                        - Priority: Medium
                                 ShowZombieCount:
                                        - Author: Build
                                        - Version: 2.0.2
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: show_zombie_count
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 5.2.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 5.2.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 Ultimate-AFK:
                                        - Author: SrLicht
                                        - Version: 5.0.2
                                        - Required Exiled Version: 5.1.1
                                        - Prefix: Ultimate_Afk
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 5.2.1.0
                                        - Required Exiled Version: 5.2.1.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 XPSystem:
                                        - Author: nutmaster#4861
                                        - Version: 1.1.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: x_p_system
                                        - Priority: Medium
                                 BetterSinkholes:
                                        - Author: Build
                                        - Version: 4.0.1
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: better_sinkholes
                                        - Priority: Medium
**Additional context**
it's not always tho. Just sometimes auto nuke starts when round starts

**Comment by Marco15453** [comment]
Is this issue still occur?

**Comment by Marco15453** [comment]
Closed due to no answer
