### ISSUE TITLE
NukeLock throws an exception when trying to disable

### ISSUE THREAD

**Issue by Skillz2play** [Marco15453/NukeLock#5]
**Describe the bug**
When trying to cancel the nuke, it throws an exception

**To Reproduce**
1. Install NukeLock
2. Click on big red button to disable
3. See exception

**Expected behavior**
I would expect it to disable but it doesn't

**Screenshots**

**Server logs**

https://pastebin.com/ah5B4kwa

**NukeLock Version ("latest" is not a version):**
v1.7.0

**Results of `show plugins` command in console:**
                                 Enabled plugins: 31
                                 Disabled plugins: 10
                                 
                                 Buddy:
                                        - Author: DGvagabond
                                        - Version: 1.4.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: buddy
                                        - Priority: Highest
                                 CedMod:
                                        - Author: ced777ric#0001
                                        - Version: 3.0.1
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: cm
                                        - Priority: Highest
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 4.2.2.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 SCPAliveStatus:
                                        - Author: Marco15453
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: s_c_p_alive_status
                                        - Priority: Medium
                                 RainbowTags:
                                        - Author: FruitBoi & Build & iRebbok
                                        - Version: 2.3.3.0
                                        - Required Exiled Version: 3.0.5
                                        - Prefix: rainbow_tags
                                        - Priority: Medium
                                 LogArchiver:
                                        - Disabled
                                        - Author: Galaxy119
                                        - Version: 1.0.0
                                        - Required Exiled Version: 2.1.18
                                        - Prefix: LogArchiver
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 4.2.2.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 Better079:
                                        - Disabled
                                        - Author: MrAfitol
                                        - Version: 1.2.1
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: better079
                                        - Priority: Medium
                                 Better Mute:
                                        - Author: Killla
                                        - Version: 1.0.4
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: BetterMute
                                        - Priority: Medium
                                 HealSCPs:
                                        - Author: Skillz2play
                                        - Version: 1.4.2
                                        - Required Exiled Version: 4.0.0
                                        - Prefix: heal_s_c_ps
                                        - Priority: Medium
                                 AnimatedServerTitle:
                                        - Author: Killers0992
                                        - Version: 1.0.1
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: animatedservertitle
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Author: Exiled Team
                                        - Version: 5.0.2.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium
                                 MapEditorReborn:
                                        - Disabled
                                        - Author: Michal78900 (original idea by Killers0992)
                                        - Version: 1.2.3
                                        - Required Exiled Version: 3.7.2
                                        - Prefix: map_editor_reborn
                                        - Priority: Medium
                                 Stalky106:
                                        - Author: RogerFK
                                        - Version: 3.0.0.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: ST106
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Galaxy119
                                        - Version: 5.0.3.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 Gamemode Manager:
                                        - Author: Galaxy119
                                        - Version: 1.1.2
                                        - Required Exiled Version: 2.1.12
                                        - Prefix: gamemode_manager
                                        - Priority: Medium
                                 CustomRoles:
                                        - Author: Galaxy119
                                        - Version: 2.0.0.0
                                        - Required Exiled Version: 4.1.5
                                        - Prefix: CustomRoles
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 3.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Medium
                                 WaitAndChillReborn:
                                        - Disabled
                                        - Author: Michal78900
                                        - Version: 4.0.0
                                        - Required Exiled Version: 4.1.2
                                        - Prefix: wait_and_chill_reborn
                                        - Priority: Medium
                                 BetterSinkholes2:
                                        - Author: 
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: better_sinkholes2
                                        - Priority: Medium
                                 CustomItems:
                                        - Author: Exiled Team
                                        - Version: 4.0.2.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: custom_items
                                        - Priority: Medium
                                 ElevatorLockdown:
                                        - Author: Marco15453
                                        - Version: 1.8.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: elevator_lockdown
                                        - Priority: Medium
                                 Guys who know how to make such a thing:
                                        - Author: Dark7eamplar#2683
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 3.0.5
                                        - Prefix: gwkhtmsat
                                        - Priority: Medium
                                 BetterDrops:
                                        - Disabled
                                        - Author: Jesus-QC
                                        - Version: 1.0.1
                                        - Required Exiled Version: 4.1.7
                                        - Prefix: better_drops
                                        - Priority: Medium
                                 Ultimate AFK:
                                        - Disabled
                                        - Author: Thomasjosif
                                        - Version: 3.1.6
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: uAFK
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 4.2.2.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Disabled
                                        - Author: Exiled Team
                                        - Version: 4.2.2.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Npcs:
                                        - Disabled
                                        - Author: Jesus-QC
                                        - Version: 0.0.1
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: Npcs
                                        - Priority: Medium
                                 ShowZombieCount:
                                        - Author: Naku (Cwaniaak.)
                                        - Version: 1.4.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: show_zombie_count
                                        - Priority: Medium
                                 Pets:
                                        - Disabled
                                        - Author: Jesus-QC
                                        - Version: 0.0.1
                                        - Required Exiled Version: 2.1.15
                                        - Prefix: Pets
                                        - Priority: Medium
                                 SupplyDrop:
                                        - Disabled
                                        - Author: Wafel, KadeDev, JesusQC
                                        - Version: 3.0.0
                                        - Required Exiled Version: 4.0.0
                                        - Prefix: SD
                                        - Priority: Medium
                                 NukeLock:
                                        - Author: Marco15453
                                        - Version: 1.6.0
                                        - Required Exiled Version: 3.0.5
                                        - Prefix: nuke_lock
                                        - Priority: Medium
                                 ScpSwap:
                                        - Author: Originally written by Cyanox, modifications by KoukoCocoa & Thomasjosif
                                        - Version: 1.3.2
                                        - Required Exiled Version: 2.1.29.0
                                        - Prefix: scp_swap
                                        - Priority: Medium
                                 CedMod-WebAPI:
                                        - Author: ced777ric#0001
                                        - Version: 3.0.1
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: cm_WAPI
                                        - Priority: Medium
                                 Scp096Info:
                                        - Author: VersLugia
                                        - Version: 1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: scp096_info
                                        - Priority: Medium
                                 Polls:
                                        - Author: 
                                        - Version: 1.1.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: polls
                                        - Priority: Medium
                                 WhoAreMyTeamates?:
                                        - Author: XoMiya-WPC & TheUltiOne
                                        - Version: 3.2.1
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: Who_Are_My_Teammates
                                        - Priority: Medium
                                 ShowReportsInGame:
                                        - Author: Denty
                                        - Version: 1.1.0
                                        - Required Exiled Version: 4.1.0
                                        - Prefix: ShowReportsInGame
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 4.2.2.0
                                        - Required Exiled Version: 4.2.2.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 SCPStats:
                                        - Author: PintTheDragon
                                        - Version: 1.5.1
                                        - Required Exiled Version: 4.1.7
                                        - Prefix: scp_stats
                                        - Priority: Lowest
**Additional context**

**Comment by Marco15453** [comment]
Bug should be Fixed in Release v1.7.1
