### ISSUE TITLE
Radiation occouring randomly at beginning of round.

### ISSUE THREAD

**Issue by DinoNuggets2** [Marco15453/NukeLock#7]
**Describe the bug**
Radiation beginning randomly at the beginning of the round

**To Reproduce**
1. Start a new round
2. Check your health
(It happens rarely, for me every 10-30 rounds)

**Expected behavior**
Expecting radiation to occur when the configurable time reaches 0

**Screenshots**
Couldn't get one.

**Server logs**
I didn't get look at the logs when it happened last, if it happens again I will try to.

**NukeLock Version ("latest" is not a version):**
1.7.0

**Results of `show plugins` command in console:**
                           Enabled plugins: 30
                           Disabled plugins: 0
                           
                           Exiled.Events:
                                - Author: Exiled Team
                                - Version: 4.2.2.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_events
                                - Priority: Highest
                           Spectator Shooting Range:
                                - Author: rayzer
                                - Version: 2.0.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: spectator_shooting_range
                                - Priority: Higher
                           CustomItems:
                                - Author: Exiled Team
                                - Version: 4.0.2.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_items
                                - Priority: Medium
                           Exiled.CreditTags:
                                - Author: Babyboucher20 & iRebbok & Exiled Team
                                - Version: 4.2.2.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_credits
                                - Priority: Medium
                           NukeLock:
                                - Author: Marco15453
                                - Version: 1.7.0
                                - Required Exiled Version: 4.2.2
                                - Prefix: nuke_lock
                                - Priority: Medium
                           WaitAndChillReborn:
                                - Author: Michal78900
                                - Version: 4.0.0
                                - Required Exiled Version: 4.1.2
                                - Prefix: wait_and_chill_reborn
                                - Priority: Medium
                           LightsRE:
                                - Author: Beryl - (Contributors: BuildBoy12)
                                - Version: 4.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: lights
                                - Priority: Medium
                           Exiled.CustomItems:
                                - Author: Exiled Team
                                - Version: 4.2.2.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_custom_items
                                - Priority: Medium
                           UIURescueSquad:
                                - Author: JesusQC, maintained by Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: UIURescueSquad
                                - Priority: Medium
                           RespawnTimer:
                                - Author: Michal78900
                                - Version: 3.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: respawn_timer
                                - Priority: Medium
                           Stalky106:
                                - Author: RogerFK
                                - Version: 3.0.0.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: ST106
                                - Priority: Medium
                           CustomWarheadColor:
                                - Author: SoraCént
                                - Version: 0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: custom_warhead_color
                                - Priority: Medium
                           Exiled.Updater:
                                - Author: Exiled.Updater
                                - Version: 3.1.1.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_updater
                                - Priority: Medium
                           Infiltrated:
                                - Author: Twitch.tv/Monaldcry7788#9248
                                - Version: 5.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: infiltrated
                                - Priority: Medium
                           Scp035:
                                - Author: Joker119
                                - Version: 4.0.2
                                - Required Exiled Version: 4.2.0
                                - Prefix: Scp035
                                - Priority: Medium
                           LeftHandedPlayers:
                                - Author: TemmieGamerGuy
                                - Version: 1.0.1
                                - Required Exiled Version: 3.0.0
                                - Prefix: left_handed_players
                                - Priority: Medium
                           CustomDoorAccess:
                                - Author: Faety
                                - Version: 1.4.0
                                - Required Exiled Version: 3.7.2
                                - Prefix: cda
                                - Priority: Medium
                           AnimatedServerTitle:
                                - Author: Killers0992
                                - Version: 1.0.1
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: animatedservertitle
                                - Priority: Medium
                           Exiled.Permissions:
                                - Author: Exiled Team
                                - Version: 4.2.2.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_permissions
                                - Priority: Medium
                           LogArchiver:
                                - Author: Galaxy119
                                - Version: 1.0.0
                                - Required Exiled Version: 2.1.18
                                - Prefix: LogArchiver
                                - Priority: Medium
                           Common Utilities:
                                - Author: Galaxy119
                                - Version: 5.1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: CommonUtilities
                                - Priority: Medium
                           SupplyDrop:
                                - Author: Wafel, KadeDev, JesusQC
                                - Version: 3.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: SD
                                - Priority: Medium
                           Exiled.CustomRoles:
                                - Author: Exiled Team
                                - Version: 4.2.2.0
                                - Required Exiled Version: 4.2.2.0
                                - Prefix: exiled_custom_roles
                                - Priority: Medium
                           SCPLockdown:
                                - Author: Raul125
                                - Version: 2.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: scp_lockdown
                                - Priority: Medium
                           SCP1162:
                                - Author: xRoier
                                - Version: 4.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: scp1162
                                - Priority: Medium
                           DiscordIntegration:
                                - Author: Exiled Team
                                - Version: 5.0.1.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: discord_integration
                                - Priority: Medium
                           MapEditorReborn:
                                - Author: Michal78900 (original idea by Killers0992)
                                - Version: 2.0.0
                                - Required Exiled Version: 4.0.0
                                - Prefix: map_editor_reborn
                                - Priority: Medium
                           Admin Tools:
                                - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                - Version: 4.0.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: AT
                                - Priority: Medium
                           BetterDrops:
                                - Author: Jesus-QC
                                - Version: 1.0.1
                                - Required Exiled Version: 4.1.7
                                - Prefix: better_drops
                                - Priority: Medium
                           Smelly096:
                                - Author: x3rt
                                - Version: 1.0.0
                                - Required Exiled Version: 3.0.0
                                - Prefix: smelly096
                                - Priority: Lowest

**Additional context**

**Comment by Marco15453** [comment]
I cannot replicate this issue!

**Comment by Marco15453** [comment]
If you have an video proof that would be helpful, because i cannot replicate it!

**Comment by DinoNuggets2** [comment]
Alright, tomorrow I will try my best to, it happens rarely, so it will be hard to get a good video of it, but I'll try

**Comment by DinoNuggets2** [comment]
I got a video of it, right before I could start recording, it put the text at the top of the screen saying the radiation leak has started. 
https://pastebin.com/SsutUSYe

https://user-images.githubusercontent.com/91291118/148701023-5c7cc45b-b8d1-46e5-a755-6824bdcb6c7a.mp4

**Comment by Marco15453** [comment]
Alright, thanks
